### ISSUE TITLE
An error Ollama API with status code 400

### ISSUE THREAD

**Issue by Taffty** [ILikeAI/AlwaysReddy#76]
I get this error code after speaking, some issue with taking to the API, I've been working on it for hours. Any suggestions?

```
Initializing action: AlwaysReddyVoiceAssistant
Voice assistant hotkeys:
'alt+ctrl+r': Start/stop talking to voice assistant (press to toggle on and off or hold-release)
        Hold down 'alt+ctrl' and double tap 'r' to send clipboard content to AlwaysReddy
'alt+ctrl+w': New chat for voice assistant

Initializing action: ReadClipboard
'ctrl+alt+c': To read the text in your clipboard aloud

Initializing action: TranscribeAndPaste
'ctrl+alt+t': Transcribe to clipboard (press to toggle on and off hold-release)

System actions:
'alt+ctrl+e': Cancel currently running action, recording, TTS or other

AlwaysReddy is reddy. Use any of the hotkeys above to get started.
Running handle_default_assistant_response...
Starting recording... Action: handle_default_assistant_response
Recording started...
Running handle_default_assistant_response...
Stopping recording...
Recording saved to audio_files\temp_recording.wav
Transcribing audio file: audio_files\temp_recording.wav
Detected language: en with probability 1.00

Transcript:
 hmm
Request failed with status code 400
Traceback (most recent call last):
  File "C:\Users\tobya\Downloads\AlwaysReddy-main\AlwaysReddy-main\llm_apis\ollama_client.py", line 55, in stream_completion
    raise RuntimeError(f"Request failed with status code {response.status_code}")
RuntimeError: Request failed with status code 400
Traceback (most recent call last):
  File "C:\Users\tobya\Downloads\AlwaysReddy-main\AlwaysReddy-main\llm_apis\ollama_client.py", line 55, in stream_completion
    raise RuntimeError(f"Request failed with status code {response.status_code}")
RuntimeError: Request failed with status code 400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tobya\Downloads\AlwaysReddy-main\AlwaysReddy-main\actions\always_reddy_voice_assistant\main.py", line 63, in handle_default_assistant_response
    response = self.AR.completion_client.process_text_stream(stream,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tobya\Downloads\AlwaysReddy-main\AlwaysReddy-main\completion_manager.py", line 162, in process_text_stream
    for chunk in text_stream:
                 ^^^^^^^^^^^
  File "C:\Users\tobya\Downloads\AlwaysReddy-main\AlwaysReddy-main\llm_apis\ollama_client.py", line 62, in stream_completion
    raise RuntimeError(f"An error occurred streaming completion from Ollama API: {e}")
RuntimeError: An error occurred streaming completion from Ollama API: Request failed with status code 400
```

**Comment by Taffty** [comment]
seems to be something with the try 

     ```
   try:
            with requests.post(url, data=json_data, stream=True, headers=headers) as response:
                if response.status_code == 200:
                    for chunk in response.iter_content(chunk_size=None):
                        if chunk:
                            # Parse the JSON response and extract the content
                            response_data = json.loads(chunk)
                            yield response_data['message']['content']
                else:
                    if self.verbose:
                        print(f"Request failed with status code {response.status_code}")
                    raise RuntimeError(f"Request failed with status code {response.status_code}")
        except Exception as e:
            if self.verbose:
                import traceback
                traceback.print_exc()
            else:
                print(f"An error occurred streaming completion from Ollama API: {e}")
            raise RuntimeError(f"An error occurred streaming completion from Ollama API: {e}")
```

Heres the config for ollama


## MAKE A COPY OF THIS CALLED config.py
VERBOSE = True
USE_GPU = False  # Set to True to use GPU acceleration. Refer to the README for instructions on installing PyTorch with CUDA support.

### HOTKEY BINDINGS ###
# Hotkeys can be set to None to disable them
CANCEL_HOTKEY = 'alt+ctrl+e'
NEW_CHAT_HOTKEY = 'alt+ctrl+w'
RECORD_HOTKEY = 'alt+ctrl+r' # Press to start, press again to stop, or hold and release. Double tap to include clipboard
READ_FROM_CLIPBOARD = "ctrl+alt+c"
TRANSCRIBE_RECORDING = "ctrl+alt+t"

### COMPLETIONS API SETTINGS  ###
# Just uncomment the ONE api you want to use

### LOCAL OPTIONS ###

## OLLAMA COMPLETIONS API EXAMPLE ##
COMPLETIONS_API = "ollama"
COMPLETION_MODEL = "llama3.1"
OLLAMA_API_BASE_URL = "http://localhost:11434" #This should be the defualt
OLLAMA_KEEP_ALIVE = "-1" # The duration that models stay loaded in memory (default "5m"). Set to "-1" to keep models loaded indefinitely

**Comment by Taffty** [comment]
SOLVED: Had keep alive set to -1, needs to be 1 or more, if you want indefinably just set the number really high.

**Comment by ILikeAI** [comment]
You can set it to be loaded indefinitely with "-1s"
