### ISSUE TITLE
Traceback (most recent call last):   File "D:\AlwaysReddy\main.py", line 3, in <module>

### ISSUE THREAD

**Issue by ctxadm** [ILikeAI/AlwaysReddy#83]
D:\AlwaysReddy>run_AlwaysReddy.bat
Traceback (most recent call last):
  File "D:\AlwaysReddy\main.py", line 3, in <module>
    from audio_recorder import AudioRecorder
  File "D:\AlwaysReddy\audio_recorder.py", line 3, in <module>
    from config_loader import config
  File "D:\AlwaysReddy\config_loader.py", line 91, in <module>
    config = ConfigLoader()
             ^^^^^^^^^^^^^^
  File "D:\AlwaysReddy\config_loader.py", line 36, in __init__
    user_config = self._import_config(user_config_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AlwaysReddy\config_loader.py", line 60, in _import_config
    spec.loader.exec_module(config)
  File "D:\AlwaysReddy\config.py", line 22
    COMPLETION_MODEL = "instructlab/granite-7b-lab"
IndentationError: unexpected indent

got this error :(

**Comment by Jobus0** [comment]
The last three lines of the error explains the problem: On line 22 in your config.py, you have an indent. Simply remove it. No line in your config.py should start with a tab indent or a space.

**Comment by ctxadm** [comment]
You're right!, thanks a lot :))
